name: Admin Panel Theme

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" and "dev" branch
    push:
      branches:    
        - main
        - dev

    # Triggers the workflow on creating the pull request events but only for the "main" and "dev" branch
    pull_request:
        branches: [ "main", "dev" ]
        
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:
        name: Build and Deploy
        runs-on: self-hosted
        steps:
            - name: Install Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'
            - name: Install Dependencies
              run: npm install --legacy-peer-deps
            - name: Build
              run: npm run build
            - name: print
              run: echo "Compeleted"